### PR TITLE
Added GPIO Set Pull-Up Pull-Down Resistor Functionality

### PR DESCRIPTION
**Pull request by mdsebald**
Added set_pull_mode/2  function to GPIO.ex module, plus associated code to implement the NIF.  
Tested on one GPIO pin so far. 

Don't know why, but I was not able to open "/dev/gpiomem", so had to open "dev/mem" instead.  That means need to get the peripheral address.  The bcm_host library was not getting linked in so I copied the code for bcm_host_get_peripheral_address() from the bcm_host library source, to get the peripheral address. (see sysfs_utils.c)

This will need some cleanup, I'm sure.

### CODE REVIEW

**Comment by fhunleth** [comment]
Nice! Can't wait to try it out.

**Comment by mdsebald** [comment]
Thanks for the .gitignore_global hint,  I was not aware of that feature
before.  Did you want the .gitignore_global file to be a part the repo,
too?

**Comment by fhunleth** [comment]
No, the `.gitignore_global` file should be in your home directory outside of any repository. The idea is that everyone maintains their own and ignores their own editors' metadata directories. It's not maintainable for everyone to add their favorite directories to ignore to every project's `.gitignore` file. You can imagine how this could get out of hand pretty quickly since everyone has their favorite editor.

**Comment by fhunleth** [comment]
I forgot that you also need to update your .gitconfig. https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Pull request merged**
